"""Adds password_hash field

Revision ID: 38c84f1e3778
Revises: c283f4ad8b7b
Create Date: 2025-06-04 18:44:13.709280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = '38c84f1e3778'
down_revision: Union[str, None] = 'c283f4ad8b7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'published_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.add_column('users', sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    op.alter_column('books', 'published_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
